package net.vicp.sealedbook.dao.auto.model;

import net.vicp.sealedbook.common.utils.BaseEntity;

public class SystemFileMo extends BaseEntity {
    /**
     * 自增主键
     */
    private Integer id;

    /**
     * 文件唯一编号
     */
    private String fileCode;

    /**
     * 文件存储目录
     */
    private String filePath;

    /**
     * @return the value of system_file.id
     * 自增主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for system_file.id
     * 自增主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of system_file.file_code
     * 文件唯一编号
     */
    public String getFileCode() {
        return fileCode;
    }

    /**
     * @param fileCode the value for system_file.file_code
     * 文件唯一编号
     */
    public void setFileCode(String fileCode) {
        this.fileCode = fileCode == null ? null : fileCode.trim();
    }

    /**
     * @return the value of system_file.file_path
     * 文件存储目录
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * @param filePath the value for system_file.file_path
     * 文件存储目录
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemFileMo other = (SystemFileMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFileCode() == null ? other.getFileCode() == null : this.getFileCode().equals(other.getFileCode()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFileCode() == null) ? 0 : getFileCode().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fileCode=").append(fileCode);
        sb.append(", filePath=").append(filePath);
        sb.append("]");
        return sb.toString();
    }
}