package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.SystemFileExample;
import net.vicp.sealedbook.dao.auto.model.SystemFileMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int countByExample(SystemFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int deleteByExample(SystemFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int insert(SystemFileMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int insertBatch(List<SystemFileMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int insertSelective(SystemFileMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    List<SystemFileMo> selectByExample(SystemFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    SystemFileMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemFileMo record, @Param("example") SystemFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemFileMo record, @Param("example") SystemFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemFileMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemFileMo record);
}